#!/usr/bin/env bash
# displays information for specified domain and subdomain

output_function() {

var=$(dig "$2.$1" | awk '/;; ANSWER SECTION:/ { getline; print $1,$4,$5 }')
v2=$(echo "$var" | awk '{ print $2 }')
v3=$(echo "$var" | awk '{ print $3 }')
v1=$(echo "$var" | awk -F '.' '{ print $1 }')

echo "The subdomain $v1 is a $v2 record and points to $v3"

}

if [ "$#" -eq 2 ]; then
    output_function "$1" "$2"
else
    elements=("www" "lb-01" "web-01" "web-02")
    for element in "${elements[@]}"; do
        output_function "$1" "$element"
    done
fi
