#!/usr/bin/env bash
# a script that configures NGINX on ubuntu server

# update package manager and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# allow directory ownership for the current user
sudo chown -R "$USER":"$USER" /var/www/html

# creating new index.html file
echo -e "Hello World!" > /var/www/html/index.html

# Define the redirect URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Define the nginx configuration file and the rewrite rule
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"
REWRITE_RULE="rewrite ^/redirect_me $REDIRECT_URL permanent;"
LINE_NUMBER="24"

# insert the rewrite directive using sed
sudo sed -i $LINE_NUMBER"i\\$REWRITE_RULE" $NGINX_CONFIG_FILE

# reload nginx
sudo service reload nginx
