#!/usr/bin/env bash
# a script that configures redirect on NGINX on ubuntu server

# update package manager and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# allow directory ownership for the current user
sudo chown -R "$USER":"$USER" /var/www/html

# creating new index.html file
echo -e "Hello World!" > /var/www/html/index.html

# Define the redirect URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Define the Nginx configuration file, rewrite rule, and line number
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"
REWRITE_RULE="\trewrite ^/redirect_me $REDIRECT_URL permanent;"
LINE_NUMBER="24"

# Insert the rewrite directive using sed
sudo sed -i "${LINE_NUMBER}i\\$REWRITE_RULE" $NGINX_CONFIG_FILE

# reload nginx
sudo service nginx restart
