#!/usr/bin/env bash
#a script that configures redirect on NGINX on ubuntu server

# update package manager and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# allow directory ownership for the current user
sudo chown -R "$USER":"$USER" /var/www/html

# creating new index.html file
echo -e "Hello World!" > /var/www/html/index.html


# Define the redirect URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# #define config file
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"

# Define the Nginx configuration file, rewrite rule, and line number
REDIRECT_RULE="\tlocation /redirect { return 301 $REDIRECT_URL; }"
LINE_NUMBER_1="53"

# Insert the redirect directive using sed
sudo sed -i "${LINE_NUMBER_1}i\\$REDIRECT_RULE" $NGINX_CONFIG_FILE

# creating new error_404.html file
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# defining 404 rule
ERROR_RULE="\terror_page 404 /error_404.html;"
LINE_NUMBER_2="54"
sudo sed -i "${LINE_NUMBER_2}i\\$ERROR_RULE" $NGINX_CONFIG_FILE

# reload nginx
sudo service nginx restart
