#!/usr/bin/env bash
# a script that configures redirect on NGINX on ubuntu server

# update package manager and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# allow directory ownership for the current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx

# creating new index.html file
echo -e "Hello World!" > /var/www/html/index.html

# creating new error_404.html file
echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html

# adding new location directive
redirect="https://www.youtube.com/watch?v=QH2-TGUlwu4"
directive="location \/redirect { return 301 $redirect; }"
nginx_conf_file="/etc/nginx/sites-available/default"

if ! grep -q "$directive" "$nginx_conf_file"; then
    sed -i '/^\t*location \/ {/ { :1; /}/!{N;b1}; s|}|&\n\t'"$directive"'| }' "$nginx_conf_file"
fi

# adding error directive
directive="error_page 404 \/error_404.html;"
nginx_conf_file="/etc/nginx/sites-available/default"

if ! grep -q "$directive" "$nginx_conf_file"; then
    sed -i '/^\t*location \/ {/ { :1; /}/!{N;b1}; s|}|&\n\t'"$directive"'| }' "$nginx_conf_file"
fi

# adding header directive
directive="add_header X-Served-By \$hostname;"
nginx_conf_file="/etc/nginx/sites-available/default"

if ! grep -q "$directive" "$nginx_conf_file"; then 
    sed -i "/^\tlocation \/ {/a\ \t\t$directive" "$nginx_conf_file"
fi

# restart nginx
sudo service nginx restart
