#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.

function sigterm {
    echo "I am invincible!!!"
}

trap 'sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
