#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# "bad luck" on 4 "good luck" on 8.

count=10
i=0

while [ $i -lt $count ]
do
    if [ $i == 3 ]; then
        echo "bad luck"
    elif [ $i == 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done