#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

h_limit=13
m_limit=59

h=0
m=1
while [ $h -lt $h_limit ]
do
    echo "Hour: $h"
    while [ $m -le $m_limit ]
    do
        echo "$m"
        m=$((m+1))
    done
    h=$((h+1))
    m=1
done
