#!/usr/bin/env bash
# Define a function to update nginx configuration
# Stop nginx service
service nginx stop

# Change nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Start nginx service
service nginx start

