#!/usr/bin/env bash

# Define a function to update nginx configuration
config_file="/etc/nginx/nginx.conf"
default_file="/etc/nginx/sites-enabled/default"

chmod a+x "$config_file"
sed -iE 's/\s*#?\s*user .*/user nginx;/' "$config_file"
sed -iE 's/(listen (\[::\]:)?80) /\180 /' "$default_file"
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
