#!/usr/bin/env bash
# Define a function to update nginx configuration
service nginx stop
sed -iE 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -iE 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
service nginx start
